from __future__ import annotations

import pytest

from project_docs import build_architecture_mermaid, build_module_map, build_overview_paragraph, build_readme

pytestmark = pytest.mark.unit


def _write(path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def test_build_module_map_categorizes_real_files_and_excludes_noise(tmp_path):
    _write(tmp_path / "src" / "routes" / "api.py", "# route")
    _write(tmp_path / "src" / "models" / "user.py", "class User: pass")
    _write(tmp_path / "tests" / "test_user.py", "def test_x(): pass")
    _write(tmp_path / "node_modules" / "some_dep" / "index.js", "module.exports = {}")
    _write(tmp_path / ".git" / "config", "[core]")

    module_map = build_module_map(tmp_path)

    assert "src/routes/api.py" in module_map["routes/controllers"]
    assert "src/models/user.py" in module_map["models"]
    assert "tests/test_user.py" in module_map["tests"]
    all_paths = [path for paths in module_map.values() for path in paths]
    assert not any("node_modules" in path for path in all_paths)
    assert not any(".git" in path for path in all_paths)


def test_build_module_map_returns_only_non_empty_areas(tmp_path):
    _write(tmp_path / "plain.py", "print('hi')")

    module_map = build_module_map(tmp_path)

    assert all(len(paths) > 0 for paths in module_map.values())


def test_build_architecture_mermaid_reflects_real_module_map():
    module_map = {"models": ("src/models/user.py",), "tests": ("tests/test_user.py", "tests/test_other.py")}

    diagram = build_architecture_mermaid(module_map, "Demo Project")

    assert "```mermaid" in diagram
    assert "flowchart TD" in diagram
    assert '["Demo Project"]' in diagram
    assert "models (1 file)" in diagram
    assert "tests (2 files)" in diagram
    assert "src/models/user.py" in diagram
    assert "tests/test_user.py" in diagram


def test_build_overview_paragraph_states_the_goal_and_the_audience():
    overview = build_overview_paragraph("Build a demo API", ("Single local user",))

    assert overview == "Build a demo API. Built for a single local user."


def test_build_overview_paragraph_keeps_existing_terminal_punctuation():
    overview = build_overview_paragraph("Does this work?", ())

    assert overview == "Does this work?"


def test_build_overview_paragraph_omits_the_audience_sentence_when_unknown():
    overview = build_overview_paragraph("Build a demo API.", ())

    assert overview == "Build a demo API."


def test_build_overview_paragraph_lists_several_audiences():
    overview = build_overview_paragraph("Build a demo API.", ("A small internal team", "Public users"))

    assert overview == "Build a demo API. Built for a small internal team and public users."


def test_build_overview_paragraph_falls_back_when_the_goal_is_blank():
    overview = build_overview_paragraph("   ", ())

    assert overview == "This project was generated by AI Freelance Studio."


def test_build_overview_paragraph_truncates_an_overlong_goal_on_a_word_boundary():
    # brief.goal is LongText and can carry a whole pasted specification, so the README
    # opener has to stay readable without slicing a word in half.
    overview = build_overview_paragraph(" ".join(["alpha"] * 300), ())

    assert len(overview) <= 504  # 500-char cap plus the "..." marker
    assert overview.endswith("...")
    assert "alph..." not in overview


def test_build_overview_paragraph_collapses_whitespace():
    overview = build_overview_paragraph("Build\n\na   demo\tAPI.", ())

    assert overview == "Build a demo API."


def test_build_readme_contains_every_real_substituted_value():
    module_map = {"models": ("src/models/user.py",)}

    readme = build_readme(
        project_name="Demo Project",
        goal="Build a demo API",
        tech_stack="Frontend: React\nBackend: FastAPI\nStorage: SQLite",
        features=("Real-time chat", "User auth"),
        run_instruction="Install dependencies with `pip install -r requirements.txt`, then start it with `uvicorn main:app`.",
        module_map=module_map,
        overview="A real overview paragraph.",
    )

    assert "# Demo Project" in readme
    assert "A real overview paragraph." in readme
    assert "- Real-time chat" in readme
    assert "- User auth" in readme
    assert "Frontend: React" in readme
    assert "pip install -r requirements.txt" in readme
    assert "ARCHITECTURE.md" in readme
    assert "**models** (1 file)" in readme


def test_the_readme_tells_the_client_how_to_run_the_project_not_how_it_was_tested():
    """A single-file page's README said `npm test` -- the QA gate's command, printed under
    "Setup / Run" -- while delivery_report.md in the same folder said to open the file in a
    browser. Two documents, one question, opposite answers, in the same delivered folder."""
    readme = build_readme(
        project_name="Pricing Page",
        goal="Three pricing tiers on one page",
        tech_stack="Frontend: Single-file HTML + inline JS (no framework, no build)",
        features=("Three tiers",),
        run_instruction="Open `index.html` in any browser. There is nothing to install and nothing to start.",
        module_map={},
        overview="A pricing page.",
    )

    assert "Open `index.html` in any browser." in readme
    assert "npm test" not in readme


def test_every_generated_file_appears_in_the_map_exactly_once(tmp_path):
    """Measured on a delivered reading journal: 29 source files walked, 18 in the map. Every
    page, the app entry, the state context and the theme hook were missing from the client's
    architecture diagram, while two components were counted twice."""
    for rel in (
        "src/App.jsx", "src/main.jsx", "index.html",
        "src/pages/BookDetail.jsx", "src/hooks/useTheme.jsx", "src/context/BooksContext.jsx",
        "src/components/DataTable.jsx", "src/styles/theme.css", "src/data/mockBooks.js",
        "src/App.test.jsx", "vite.config.js",
    ):
        _write(tmp_path / rel, "// x")

    module_map = build_module_map(tmp_path)
    listed = [path for paths in module_map.values() for path in paths]

    assert len(listed) == len(set(listed)) == 11


def test_a_form_component_is_not_filed_under_the_database(tmp_path):
    """`AddBookForm.jsx` was filed under "repositories/data" because "ad(db)ookform" contains
    the substring "db". Keywords match whole words in a path segment now."""
    _write(tmp_path / "src" / "components" / "AddBookForm.jsx", "// x")

    module_map = build_module_map(tmp_path)

    assert module_map.get("repositories/data") is None
    assert "src/components/AddBookForm.jsx" in module_map["components"]


def test_the_directory_a_file_lives_in_beats_its_own_name(tmp_path):
    """`components/DataTable.jsx` is a component, not data; `styles/components.css` is a
    stylesheet, not a component."""
    _write(tmp_path / "src" / "components" / "DataTable.jsx", "// x")
    _write(tmp_path / "src" / "styles" / "components.css", "/* x */")

    module_map = build_module_map(tmp_path)

    assert "src/components/DataTable.jsx" in module_map["components"]
    assert "src/styles/components.css" in module_map["styles"]


def test_the_entry_point_is_named_rather_than_left_unfiled(tmp_path):
    _write(tmp_path / "src" / "App.jsx", "// x")
    _write(tmp_path / "notes.js", "// x")

    module_map = build_module_map(tmp_path)

    assert "src/App.jsx" in module_map["entry points"]
    assert "notes.js" in module_map["other files"]
