"""Domain and services for the user-facing project order workflow."""

from .brief_service import (
    BriefApprovalBinding,
    BriefRevisionKind,
    BriefRevisionOperation,
    BriefRevisionRecord,
    BriefRevisionRequest,
    BriefServiceError,
    ProjectBriefService,
    verify_brief_approval,
)
from .clarification import (
    AlexClarificationService,
    ClarificationError,
    ClarificationResult,
    ClarificationSession,
    GapAnalysis,
    RequirementDimension,
    RequirementSignals,
    detect_requirement_gaps,
    infer_requirement_signals,
)
from .handoffs import AgentHandoffService
from .execution import ExecutionServiceError, ProjectExecutionService, TERMINAL_EXECUTION_STATUSES
from .execution_plan import ProductionExecutionPackage, build_production_execution_package
from .executors import (
    CancellationToken,
    ExecutionEventSink,
    ExecutionRequest,
    FakeExecutorConfig,
    FakeProjectExecutionAdapter,
    ProjectExecutionAdapter,
)
from .models import (
    AgentHandoff,
    ArtifactKind,
    ClarificationAnswer,
    ClarificationQuestion,
    ElenaDesignChoice,
    ElenaDesignConcept,
    EventKind,
    EventLevel,
    ExecutionArtifact,
    ExecutionBlocker,
    ExecutionEvent,
    ExecutionMode,
    ExecutionResult,
    ExecutionStage,
    ExecutionStatus,
    ProjectBrief,
    ProjectExecution,
    ProductType,
    QuestionType,
    RecommendedStack,
    TestSummary,
    ThemePalette,
    UserOrder,
    UserOrderStatus,
    append_bounded_event,
    new_public_id,
    utc_now,
)
from .persistence import ExecutionStateStore, InMemoryExecutionStateStore
from .production_adapter import ProductionProjectExecutionAdapter
from .readiness import ReadinessResult, readiness_blocker
from .service import OrderWorkflowError, OrderWorkflowService
from .transitions import (
    InvalidWorkflowTransition,
    validate_execution_stage_transition,
    validate_execution_transition,
    validate_order_transition,
)

__all__ = [
    "AlexClarificationService",
    "AgentHandoff",
    "AgentHandoffService",
    "ArtifactKind",
    "BriefApprovalBinding",
    "BriefRevisionKind",
    "BriefRevisionOperation",
    "BriefRevisionRecord",
    "BriefRevisionRequest",
    "BriefServiceError",
    "ClarificationAnswer",
    "ClarificationError",
    "ClarificationQuestion",
    "ClarificationResult",
    "ClarificationSession",
    "ElenaDesignChoice",
    "ElenaDesignConcept",
    "EventKind",
    "EventLevel",
    "ExecutionArtifact",
    "ExecutionBlocker",
    "ExecutionEvent",
    "ExecutionEventSink",
    "ExecutionMode",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionServiceError",
    "ExecutionStage",
    "ExecutionStateStore",
    "ExecutionStatus",
    "FakeExecutorConfig",
    "FakeProjectExecutionAdapter",
    "GapAnalysis",
    "InvalidWorkflowTransition",
    "InMemoryExecutionStateStore",
    "ProjectBrief",
    "ProjectBriefService",
    "ProjectExecution",
    "ProjectExecutionAdapter",
    "ProjectExecutionService",
    "ProductionExecutionPackage",
    "ProductionProjectExecutionAdapter",
    "OrderWorkflowError",
    "OrderWorkflowService",
    "ProductType",
    "QuestionType",
    "RecommendedStack",
    "RequirementDimension",
    "RequirementSignals",
    "ReadinessResult",
    "TestSummary",
    "ThemePalette",
    "TERMINAL_EXECUTION_STATUSES",
    "UserOrder",
    "UserOrderStatus",
    "append_bounded_event",
    "build_production_execution_package",
    "detect_requirement_gaps",
    "infer_requirement_signals",
    "new_public_id",
    "readiness_blocker",
    "utc_now",
    "validate_execution_stage_transition",
    "validate_execution_transition",
    "validate_order_transition",
    "verify_brief_approval",
]
