"""Domain and services for the user-facing project order workflow."""

from .brief_service import (
    BriefApprovalBinding,
    BriefRevisionKind,
    BriefRevisionOperation,
    BriefRevisionRecord,
    BriefRevisionRequest,
    BriefServiceError,
    ProjectBriefService,
    verify_brief_approval,
)
from .clarification import (
    AlexClarificationService,
    ClarificationError,
    ClarificationResult,
    ClarificationSession,
    GapAnalysis,
    RequirementDimension,
    RequirementSignals,
    detect_requirement_gaps,
    infer_requirement_signals,
)
from .design_preview import (
    DesignPreview,
    DesignPreviewError,
    DesignPreviewService,
    DesignPreviewStatus,
    LayoutArchetype,
    PreviewLayout,
    PreviewScreen,
    design_preview_handoff_lines,
    verify_design_preview_approval,
)
from .handoffs import AgentHandoffService
from .execution import ExecutionServiceError, ProjectExecutionService, TERMINAL_EXECUTION_STATUSES
from .execution_config import ExecutionConfigurationProvider, ExecutionConfigurationSnapshot
from .execution_readiness import ExecutionReadinessBlocker, ExecutionReadinessCheck, ExecutionReadinessView
from .execution_plan import ProductionExecutionPackage, build_production_execution_package
from .executors import (
    CancellationToken,
    ExecutionEventSink,
    ExecutionRequest,
    FakeExecutorConfig,
    FakeProjectExecutionAdapter,
    ProjectExecutionAdapter,
)
from .models import (
    AgentHandoff,
    ArtifactKind,
    ClarificationAnswer,
    ClarificationQuestion,
    ElenaDesignChoice,
    ElenaDesignConcept,
    EventKind,
    EventLevel,
    ExecutionArtifact,
    ExecutionBlocker,
    ExecutionEvent,
    ExecutionMode,
    ExecutionResult,
    ExecutionStage,
    ExecutionStatus,
    ProjectBrief,
    ProjectExecution,
    ProductType,
    QuestionType,
    RecommendedStack,
    TestSummary,
    ThemePalette,
    UserOrder,
    UserOrderStatus,
    append_bounded_event,
    new_public_id,
    utc_now,
)
from .persistence import ExecutionStateStore, InMemoryExecutionStateStore
from .phase_context import PhaseContext, build_phase_context
from .phased_adapter import PhasedLiveOpenCodeExecutionAdapter, resolve_execution_pipeline_mode
from .production_adapter import ProductionProjectExecutionAdapter
from .production_adapter import LiveOpenCodeExecutionAdapter, OpenCodeExecutionClient, OpenCodeExecutionResult, live_opencode_execution_enabled
from .readiness import ReadinessResult, readiness_blocker
from .service import OrderWorkflowError, OrderWorkflowService
from .transitions import (
    InvalidWorkflowTransition,
    validate_execution_stage_transition,
    validate_execution_transition,
    validate_order_transition,
)

__all__ = [
    "AlexClarificationService",
    "AgentHandoff",
    "AgentHandoffService",
    "ArtifactKind",
    "BriefApprovalBinding",
    "BriefRevisionKind",
    "BriefRevisionOperation",
    "BriefRevisionRecord",
    "BriefRevisionRequest",
    "BriefServiceError",
    "ClarificationAnswer",
    "ClarificationError",
    "ClarificationQuestion",
    "ClarificationResult",
    "ClarificationSession",
    "DesignPreview",
    "DesignPreviewError",
    "DesignPreviewService",
    "DesignPreviewStatus",
    "ElenaDesignChoice",
    "ElenaDesignConcept",
    "EventKind",
    "EventLevel",
    "ExecutionArtifact",
    "ExecutionConfigurationProvider",
    "ExecutionConfigurationSnapshot",
    "ExecutionBlocker",
    "ExecutionReadinessBlocker",
    "ExecutionReadinessCheck",
    "ExecutionReadinessView",
    "ExecutionEvent",
    "ExecutionEventSink",
    "ExecutionMode",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionServiceError",
    "ExecutionStage",
    "ExecutionStateStore",
    "ExecutionStatus",
    "FakeExecutorConfig",
    "FakeProjectExecutionAdapter",
    "GapAnalysis",
    "InvalidWorkflowTransition",
    "LayoutArchetype",
    "LiveOpenCodeExecutionAdapter",
    "OpenCodeExecutionClient",
    "OpenCodeExecutionResult",
    "InMemoryExecutionStateStore",
    "ProjectBrief",
    "ProjectBriefService",
    "ProjectExecution",
    "ProjectExecutionAdapter",
    "ProjectExecutionService",
    "ProductionExecutionPackage",
    "ProductionProjectExecutionAdapter",
    "OrderWorkflowError",
    "OrderWorkflowService",
    "PhaseContext",
    "PhasedLiveOpenCodeExecutionAdapter",
    "ProductType",
    "PreviewLayout",
    "PreviewScreen",
    "QuestionType",
    "RecommendedStack",
    "RequirementDimension",
    "RequirementSignals",
    "ReadinessResult",
    "TestSummary",
    "ThemePalette",
    "TERMINAL_EXECUTION_STATUSES",
    "UserOrder",
    "UserOrderStatus",
    "append_bounded_event",
    "design_preview_handoff_lines",
    "build_phase_context",
    "build_production_execution_package",
    "detect_requirement_gaps",
    "infer_requirement_signals",
    "live_opencode_execution_enabled",
    "new_public_id",
    "readiness_blocker",
    "resolve_execution_pipeline_mode",
    "utc_now",
    "validate_execution_stage_transition",
    "validate_execution_transition",
    "validate_order_transition",
    "verify_design_preview_approval",
    "verify_brief_approval",
]
