"""The last link in the chain: prove the generated project actually runs.

`npm run build` proves it compiles and the Playwright smoke check proves it renders under
a dev preview server -- neither proves the thing can be shipped. This module containerises
the built app the way it would actually be deployed (production static server, no dev
tooling, no host node_modules) and probes it over HTTP from outside the container.

Deliberately opt-in (FREELANCERSTUDIO_ENABLE_CONTAINER_DEPLOY=1): a Docker image build per
order costs minutes, and the studio's job is generating projects rather than hosting them.
This is the gate you switch on when you want proof the artifact runs, not a tax on every
order.

A deploy failure is reported as a warning on an otherwise successful delivery rather than
failing the execution: the generated project can be perfectly good while the host's Docker
daemon is busy, out of disk, or offline.
"""

from __future__ import annotations

import os
import re
import socket
import urllib.error
import urllib.request
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from time import monotonic, sleep

from .docker_qa_runner import DockerUnavailableError, _default_client_factory

_LOG_TAIL_CHARS = 4000
_CONTAINER_PORT = 3000
_DEFAULT_BUILD_TIMEOUT_SECONDS = 600
_PROBE_ATTEMPTS = 30
_PROBE_INTERVAL_SECONDS = 1.0

# Multi-stage on purpose: the build stage carries the toolchain, the runtime stage carries
# only the compiled assets and a static server. `serve -s` rewrites unknown paths to
# index.html, which is what a client-side-routed single-page app needs.
_DOCKERFILE = """# Generated by AI Freelance Studio -- production container for this project.
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci || npm install
COPY . .
RUN npm run build

FROM node:20-slim
WORKDIR /app
RUN npm install -g serve@14
COPY --from=build /app/dist ./dist
EXPOSE {port}
CMD ["serve", "-s", "dist", "-l", "{port}"]
""".format(port=_CONTAINER_PORT)

# Without this the `COPY . .` above would drop the HOST's node_modules into the image,
# overwriting the ones just installed for Linux -- the same platform-mismatch class of bug
# that already bit the Docker QA runner (native binaries built for the host OS).
_DOCKERIGNORE = "node_modules\ndist\n.git\n*.log\n"


def _client_image_name(app_name: str, image_tag: str) -> str:
    """A tag the client can type. Docker allows lowercase letters, digits and `._-`, and
    the name has to start with one of the first two."""
    slug = re.sub(r"[^a-z0-9]+", "-", (app_name or "").casefold()).strip("-")[:40]
    if slug and slug[0].isalnum():
        return slug
    fallback = image_tag.rsplit("/", 1)[-1].split(":", 1)[0]
    return fallback or "app"


def client_run_instruction(app_name: str, image_tag: str) -> str:
    """How the *client* starts this delivery, on their machine.

    Not `docker run <image_tag>`, which is what this module ran and what both delivered
    documents printed until 2026-08-28. That image exists in one place -- the Docker daemon
    that built it, here -- and was never pushed anywhere. On the client's machine the command
    finds no such image, tries to pull it from Docker Hub, and fails. What they do have is
    the Dockerfile in the folder, which is what these two lines use.
    """
    name = _client_image_name(app_name, image_tag)
    return "\n".join(
        (
            "```",
            f"docker build -t {name} .",
            f"docker run --rm -p {_CONTAINER_PORT}:{_CONTAINER_PORT} {name}",
            "```",
            "",
            f"Then open http://localhost:{_CONTAINER_PORT} in a browser.",
        )
    )


@dataclass(frozen=True, slots=True)
class DeploymentOutcome:
    succeeded: bool
    image_tag: str
    status_message: str
    run_command: str = ""
    served_status: int | None = None
    body_excerpt: str = ""
    logs_tail: str = ""
    duration_seconds: float = 0.0


def container_deploy_enabled(environ: dict[str, str] | None = None) -> bool:
    return (environ or os.environ).get("FREELANCERSTUDIO_ENABLE_CONTAINER_DEPLOY", "").strip() == "1"


def _free_host_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _probe(url: str) -> tuple[int | None, str]:
    """Poll until the container answers. A fresh container needs a moment to bind."""
    last_error = ""
    for _ in range(_PROBE_ATTEMPTS):
        try:
            with urllib.request.urlopen(url, timeout=3) as response:
                body = response.read(2048).decode("utf-8", errors="replace")
                return int(response.status), body
        except urllib.error.HTTPError as exc:
            # A real HTTP answer, just not a 2xx -- the server is up, so stop polling.
            return int(exc.code), exc.read(512).decode("utf-8", errors="replace")
        except Exception as exc:
            last_error = str(exc)
            sleep(_PROBE_INTERVAL_SECONDS)
    return None, last_error


def build_and_verify_container(
    workspace_path: Path,
    *,
    image_tag: str,
    app_name: str = "",
    docker_client_factory: Callable[[], object] | None = None,
    build_timeout_seconds: int = _DEFAULT_BUILD_TIMEOUT_SECONDS,
) -> DeploymentOutcome:
    """Build the project's production image, run it, and confirm it serves over HTTP.

    Never raises: every failure mode comes back as a DeploymentOutcome with
    succeeded=False so the caller can record a warning and still deliver the project.
    """
    started = monotonic()
    if not (workspace_path / "package.json").is_file():
        return DeploymentOutcome(
            succeeded=False,
            image_tag=image_tag,
            status_message="No package.json in the workspace; nothing to containerise.",
            duration_seconds=round(monotonic() - started, 2),
        )

    (workspace_path / "Dockerfile").write_text(_DOCKERFILE, encoding="utf-8")
    (workspace_path / ".dockerignore").write_text(_DOCKERIGNORE, encoding="utf-8")

    factory = docker_client_factory or _default_client_factory
    try:
        client = factory()
        client.ping()
    except Exception as exc:
        raise DockerUnavailableError(f"Docker engine is not reachable: {exc}") from exc

    try:
        client.images.build(
            path=str(workspace_path.resolve()),
            tag=image_tag,
            rm=True,
            forcerm=True,
            timeout=build_timeout_seconds,
        )
    except Exception as exc:
        return DeploymentOutcome(
            succeeded=False,
            image_tag=image_tag,
            status_message="Container image build failed.",
            logs_tail=str(exc)[-_LOG_TAIL_CHARS:],
            duration_seconds=round(monotonic() - started, 2),
        )

    host_port = _free_host_port()
    container = None
    try:
        container = client.containers.run(
            image_tag,
            detach=True,
            ports={f"{_CONTAINER_PORT}/tcp": host_port},
        )
        status, body = _probe(f"http://127.0.0.1:{host_port}/")
        logs = ""
        try:
            logs = container.logs().decode("utf-8", errors="replace")
        except Exception:
            pass

        served = status is not None and 200 <= status < 400 and bool(body.strip())
        return DeploymentOutcome(
            succeeded=served,
            image_tag=image_tag,
            status_message=(
                f"Container served HTTP {status} from the production image."
                if served
                else f"Container did not serve the app (status={status})."
            ),
            run_command=client_run_instruction(app_name, image_tag),
            served_status=status,
            body_excerpt=body[:500],
            logs_tail=logs[-_LOG_TAIL_CHARS:],
            duration_seconds=round(monotonic() - started, 2),
        )
    except Exception as exc:
        return DeploymentOutcome(
            succeeded=False,
            image_tag=image_tag,
            status_message="Container failed to start.",
            logs_tail=str(exc)[-_LOG_TAIL_CHARS:],
            duration_seconds=round(monotonic() - started, 2),
        )
    finally:
        # Always stopped: a pipeline stage that leaks running containers is a resource bug.
        # The image stays here for the operator; the client's own copy is built from the
        # delivered Dockerfile, which is what run_command tells them to do.
        if container is not None:
            try:
                container.remove(force=True)
            except Exception:
                pass
