import React, { useEffect, useState } from 'react';
import IsoOffice from './IsoOffice.jsx';

const agentMarks = { alex: 'A', maya: 'M', elena: 'E', codex: 'C', bugcatcher: 'B', sentinel: 'S', lupa: 'L', goldie: 'G', product_judge: 'PJ' };
const toolMarks = { vscode: '<>', pycharm: 'PC', cursor: 'CU', opencode: 'OC', claude: 'AI' };
const providerTabs = [{ id: 'maya', label: 'ChatGPT' }, { id: 'codex', label: 'Grok' }, { id: 'elena', label: 'Gemini' }, { id: 'lupa', label: 'Claude' }];

function statusTone(status) { return status === 'working' ? 'working' : status === 'error' ? 'error' : status === 'completed' ? 'complete' : 'idle'; }
function pretty(value) { return String(value || 'Unavailable').replace(/_/g, ' '); }

export default function StudioDashboard({ activePort, project, logs, agents, statuses, autonomousMode, onAutonomousMode, onNewProject, onSettings, onProjects, onFiles, onPush, onExport, onOpenEditor, onOpenCode, onAgentChat, onPipeline, onOpenTools }) {
  const [tasks, setTasks] = useState([]);
  const [tab, setTab] = useState('maya');
  const [chatOpen, setChatOpen] = useState(true);
  useEffect(() => { if (!project?.project_id) { setTasks([]); return; } fetch(`http://localhost:${activePort}/api/projects/${project.project_id}/tasks`).then(r => r.json()).then(d => setTasks(d.tasks || [])).catch(() => setTasks([])); }, [activePort, project?.project_id]);
  const criteria = project?.acceptance_criteria || [];
  const passed = criteria.filter(c => c.current_verdict === 'passed' || c.verdict === 'passed').length;
  const progress = criteria.length ? Math.round((passed / criteria.length) * 100) : null;
  const issues = project?.issues || [];
  const openTasks = tasks.filter(t => !['done', 'completed'].includes(t.status)).length;
  const repairs = logs.filter(line => /repair|fix attempt/i.test(line)).length;
  const eventRows = logs.slice(0, 5);
  const projectTitle = project?.title || 'No active project';
  return <div className="clean-studio-shell">
    <aside className="clean-sidebar" aria-label="Studio navigation"><div className="app-glyph">FS</div><nav>{[['Dashboard', 'dashboard'], ['Projects', 'projects'], ['AI Team', 'team'], ['Pipeline', 'pipeline'], ['Issues', 'issues'], ['Logs', 'logs'], ['Files', 'files'], ['Settings', 'settings']].map(([label, id]) => <button key={id} className={id === 'dashboard' ? 'active' : ''} onClick={() => id === 'settings' ? onSettings() : id === 'projects' ? onProjects() : id === 'files' ? onFiles() : id === 'pipeline' ? onPipeline() : null}>{label}{id === 'issues' && issues.length > 0 && <b className="issue-badge">{issues.length}</b>}</button>)}</nav><div className="autonomous-card"><span>Autonomous Mode</span><label><input type="checkbox" checked={autonomousMode} onChange={e => onAutonomousMode(e.target.checked)} /><i />{autonomousMode ? 'ON' : 'OFF'}</label></div></aside>
    <section className="clean-content"><header className="project-header"><div className="project-ident"><div className="project-glyph">{project ? 'P' : '-'}</div><div><strong>{projectTitle}</strong><span className="project-status">{pretty(project?.status)}</span><small>Branch: main <em>Project ID: {project?.project_id || '-'}</em></small></div></div><div className="pipeline-chips"><span className={passed === criteria.length && criteria.length ? 'success' : ''}>QA {criteria.length ? `${passed}/${criteria.length}` : 'unavailable'}</span><span className={project?._phase === 'review' ? 'warning' : ''}>Review {pretty(project?._phase)}</span><span className={project?.status === 'final_audit' ? 'info' : ''}>Audit {pretty(project?.status)}</span></div><div className="header-actions"><button onClick={onPush}>Push</button><button onClick={onExport}>Export</button><button onClick={onFiles}>Files</button></div></header>
      <main className="clean-main"><section className="dashboard-flow"><section className="preview-panel"><div className="section-title"><span>REAL-TIME STUDIO PLAN</span><b>Autonomous Mode: <i className={autonomousMode ? 'online' : ''}>{autonomousMode ? 'ON' : 'OFF'}</i></b></div><IsoOffice activeProject={project} activePort={activePort} agentStatuses={statuses} /></section>
        <section className="metric-row"><Metric label="Progress" value={progress === null ? 'Unavailable' : `${progress}%`} tone="blue" /><Metric label="Open Tasks" value={project ? openTasks : 'Unavailable'} tone="warning" /><Metric label="Found Issues" value={project ? issues.filter(i => i.status !== 'closed').length : 'Unavailable'} tone="danger" /><Metric label="Repair Attempts" value={project ? repairs : 'Unavailable'} tone="purple" /></section>
        <section className="studio-section"><h2>DEVELOPMENT TOOLS</h2><div className="tool-row">{[['vscode', 'VS Code'], ['pycharm', 'PyCharm'], ['cursor', 'Cursor'], ['opencode', 'OpenCode'], ['claude', 'ClaudeCode']].map(([id, name]) => <button className="tool-card" key={id} onClick={() => id === 'opencode' ? onOpenCode() : id === 'claude' ? null : onOpenEditor(id)} disabled={id === 'claude'} title={id === 'claude' ? 'ClaudeCode launcher is not configured in Studio.' : `Open in ${name}`}><b className={`tool-mark ${id}`}>{toolMarks[id]}</b><span>{name}<small>{id === 'claude' ? 'Unavailable' : 'Open'}</small></span></button>)}</div></section>
        <section className="studio-section"><h2>AI TEAM</h2><div className="team-row">{Object.entries(agents).map(([id, agent]) => { const state = statuses[id]?.status || (agent.enabled === false ? 'unavailable' : 'idle'); return <button className={`agent-card ${id === 'product_judge' ? 'judge' : ''}`} key={id} onClick={() => onAgentChat(id)}><b className="agent-mark">{agentMarks[id] || agent.name?.slice(0, 2)}</b><span>{agent.name}<small>{agent.display_role || agent.role || 'Agent'}</small></span><i className={`agent-state ${statusTone(state)}`} aria-label={state} /></button>; })}</div></section>
        <section className="bottom-row"><section className="events-panel"><h2>LATEST EVENTS</h2>{eventRows.length ? eventRows.map((event, index) => <div className="event" key={`${event}-${index}`}><i /><time>{event.match(/^\[[^\]]+\]/)?.[0] || '-'}</time><span>{event.replace(/^\[[^\]]+\]\s*/, '')}</span></div>) : <p className="empty-state">No project events are available.</p>}</section><section className="provider-panel"><h2>AI CHAT</h2><div className="provider-shortcuts">{providerTabs.map(item => <button key={item.id} onClick={() => { setTab(item.id); onAgentChat(item.id); }}><b>{item.label.slice(0, 2)}</b>{item.label}<small>{item.id === 'maya' ? 'Agent chat' : 'Available agent'}</small></button>)}</div></section></section>
      </section>{chatOpen && <aside className="right-chat"><div className="chat-title"><span>AI CHAT PANEL</span><button onClick={() => setChatOpen(false)} aria-label="Collapse AI Chat panel">-</button></div><div className="chat-tabs">{providerTabs.map(item => <button className={tab === item.id ? 'selected' : ''} key={item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div><div className="chat-body"><b>{providerTabs.find(item => item.id === tab)?.label}</b><span className="chat-availability">{agents[tab]?.enabled === false ? 'Unavailable' : 'Agent chat ready'}</span><p>Open the connected agent chat to work with current project context.</p><button className="primary-chat" onClick={() => onAgentChat(tab)}>Open {agents[tab]?.name || 'chat'}</button></div><div className="chat-input"><button aria-label="Attach file" disabled>+</button><input aria-label="Chat message" placeholder="Message in agent chat..." disabled /><button aria-label="Open chat" onClick={() => onAgentChat(tab)}>Send</button></div></aside>}<button className="chat-rail" hidden={chatOpen} onClick={() => setChatOpen(true)}>AI Chat</button></main>
    </section></div>;
}

function Metric({ label, value, tone }) { return <article className={`metric-card ${tone}`}><span>{label}</span><strong>{value}</strong><i /></article>; }
