from __future__ import annotations

from collections.abc import Callable

_MAX_OVERVIEW_LENGTH = 500


def _fallback_overview(goal: str) -> str:
    trimmed = goal.strip().rstrip(".")
    return f"{trimmed}." if trimmed else "This project was generated by AI Freelance Studio."


def generate_overview_paragraph(goal: str, features: tuple[str, ...], ai_ask: Callable[[str], str]) -> str:
    """One narrow AI call for a short prose overview. Never raises -- an unusable
    AI response degrades to a plain deterministic sentence built from `goal`,
    same fallback discipline as `design_system.generate_design_tokens`."""
    prompt = (
        "Write a single short paragraph (2-3 sentences, no more than 500 characters) introducing "
        "this software project for its README. Be concrete, not generic marketing language.\n\n"
        f"Project goal: {goal}\n"
        "Key features:\n" + "\n".join(f"- {feature}" for feature in features) + "\n\n"
        "Respond with only the paragraph text, no heading, no quotes."
    )
    try:
        raw = ai_ask(prompt).strip()
    except Exception:
        raw = ""
    if not raw:
        return _fallback_overview(goal)
    return raw[:_MAX_OVERVIEW_LENGTH]


def build_readme(
    *,
    project_name: str,
    goal: str,
    tech_stack: str,
    features: tuple[str, ...],
    setup_commands: tuple[str, ...],
    module_map: dict[str, tuple[str, ...]],
    overview: str,
) -> str:
    lines = [
        f"# {project_name}",
        "",
        "## Overview",
        "",
        overview,
        "",
        "## Features",
        "",
        *(f"- {feature}" for feature in features),
        "",
        "## Tech Stack",
        "",
        tech_stack,
        "",
        "## Setup / Run",
        "",
        "```",
        *setup_commands,
        "```",
        "",
        "## Project Structure",
        "",
        "See [ARCHITECTURE.md](ARCHITECTURE.md) for the full architecture diagram. Areas detected in this project:",
        "",
        *(f"- **{area}** ({len(files)} file{'s' if len(files) != 1 else ''})" for area, files in module_map.items()),
    ]
    return "\n".join(lines).rstrip() + "\n"
