from __future__ import annotations

_MAX_OVERVIEW_LENGTH = 500


def _truncate_on_word_boundary(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    clipped = text[:limit].rsplit(" ", 1)[0].rstrip(",;:-")
    return f"{clipped or text[:limit]}..."


def _as_sentence(text: str) -> str:
    trimmed = _truncate_on_word_boundary(" ".join(text.split()), _MAX_OVERVIEW_LENGTH)
    if not trimmed:
        return ""
    return trimmed if trimmed.endswith((".", "!", "?")) else f"{trimmed}."


# The closed set order_workflow.brief_service._target_users maps the clarification answer
# onto. Only the first needs an article to read as prose after "Built for"; the rest are
# listed so the mapping documents the full set rather than looking like a lone special
# case. Anything else is free text the user typed, and is used as-is.
_AUDIENCE_PHRASES = {
    "single local user": "a single local user",
    "a small internal team": "a small internal team",
    "customers using the application": "customers using the application",
    "public users": "public users",
}


def _join_audience(target_users: tuple[str, ...]) -> str:
    names = [" ".join(item.split()) for item in target_users if item.strip()]
    if not names:
        return ""
    # Lowercased so it reads as prose after "Built for": the brief stores these
    # capitalised ("Single local user") for display in the UI.
    phrases = [_AUDIENCE_PHRASES.get(name.casefold(), name[0].lower() + name[1:]) for name in names]
    if len(phrases) == 1:
        return phrases[0]
    return f"{', '.join(phrases[:-1])} and {phrases[-1]}"


def build_overview_paragraph(goal: str, target_users: tuple[str, ...] = ()) -> str:
    """Assemble the README's opening paragraph from the approved brief.

    This used to be one narrow AI call -- which, for the coding-CLI providers, meant a
    whole subprocess round trip per delivery to write two or three sentences. The brief
    already states what the project is and who it is for, and the README's own Features
    and Tech Stack sections cover the rest, so the model was rephrasing facts the
    document already contained and could drift from them. Deterministic assembly cannot
    drift, cannot hallucinate a feature, and costs nothing.
    """
    goal_sentence = _as_sentence(goal)
    sentences = [goal_sentence] if goal_sentence else ["This project was generated by AI Freelance Studio."]
    audience = _join_audience(target_users)
    if audience:
        sentences.append(f"Built for {audience}.")
    return " ".join(sentences)


def build_readme(
    *,
    project_name: str,
    goal: str,
    tech_stack: str,
    features: tuple[str, ...],
    run_instruction: str,
    module_map: dict[str, tuple[str, ...]],
    overview: str,
) -> str:
    lines = [
        f"# {project_name}",
        "",
        "## Overview",
        "",
        overview,
        "",
        "## Features",
        "",
        *(f"- {feature}" for feature in features),
        "",
        "## Tech Stack",
        "",
        tech_stack,
        "",
        "## Setup / Run",
        "",
        # The delivered project's own run instruction, the same string delivery_report.md
        # prints. This was the QA gate's command list until 2026-08-26, so the README of a
        # single self-contained HTML file told its client to run `npm test` -- while the
        # delivery report in the same folder correctly said to open the file in a browser.
        run_instruction,
        "",
        "## Project Structure",
        "",
        "See [ARCHITECTURE.md](ARCHITECTURE.md) for the full architecture diagram. Areas detected in this project:",
        "",
        *(f"- **{area}** ({len(files)} file{'s' if len(files) != 1 else ''})" for area, files in module_map.items()),
    ]
    return "\n".join(lines).rstrip() + "\n"
